DEFAULT_RECITER_ID = 7
TRANSLATION_ID = 20

# For QF (fill when you get LIVE credentials)
QF_CLIENT_ID = ""
QF_CLIENT_SECRET = ""
QF_AUTH_URL = ""
QF_API_BASE = ""
TOKEN_SCOPE = ""
TOKEN_EXPIRY_FALLBACK = 3600